01:07:06:| 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 101, in my_event_handler
    signal = await self.generate_signal(event)
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 43, in generate_signal
    sender = str(sender_obj.id)
AttributeError: 'NoneType' object has no attribute 'id'


09:53:38:| 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 101, in my_event_handler
    signal = await self.generate_signal(event)
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 43, in generate_signal
    sender = str(sender_obj.id)
AttributeError: 'NoneType' object has no attribute 'id'


10:43:04:| Log this exception please
/except Except:Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 107, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 93, in telegram_command
    raise Exception('Log this exception please')
Exception: Log this exception please


10:44:40:| Log this exception please
Message:/except
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 107, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 93, in telegram_command
    raise Exception('Log this exception please')
Exception: Log this exception please


13:12:41:| '<' not supported between instances of 'datetime.datetime' and 'int'
Message:/hirn
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 107, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 87, in telegram_command
    await signal_groups.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\signal_groups.py", line 14, in new_signal
    hirn_controller.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 24, in new_signal
    if not self.validate_signal(signal.message):
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 50, in validate_signal
    self.cooldown()
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 64, in cooldown
    if timenow < self.timer:
TypeError: '<' not supported between instances of 'datetime.datetime' and 'int'


13:14:45:| unsupported operand type(s) for +: 'datetime.datetime' and 'int'
Message:/hirn
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 107, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 87, in telegram_command
    await signal_groups.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\signal_groups.py", line 14, in new_signal
    hirn_controller.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 24, in new_signal
    if not self.validate_signal(signal.message):
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 50, in validate_signal
    self.cooldown()
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 69, in cooldown
    self.timer = timenow + HIRN_COOLDOWN_TIME
TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'int'


13:16:39:| 'types.SimpleNamespace' object has no attribute 'split'
Message:/hirn
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 107, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 87, in telegram_command
    await signal_groups.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\signal_groups.py", line 14, in new_signal
    hirn_controller.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 26, in new_signal
    conditions = self.parse_conditions(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 33, in parse_conditions
    result = self.parse(msg)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 75, in parse
    lines = text.split('\n')
AttributeError: 'types.SimpleNamespace' object has no attribute 'split'


14:16:31:| function missing required argument 'year' (pos 1)
Message:/hirn
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 107, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 87, in telegram_command
    await signal_groups.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\signal_groups.py", line 14, in new_signal
    hirn_controller.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 26, in new_signal
    conditions = self.parse_conditions(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 34, in parse_conditions
    result = self.parse(msg)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 91, in parse
    return [SpotBasic('Hirn', signal, coin, direction, profit_price, loss_price, timeout)]
  File "C:\Users\lachl\Documents\GitHub\telebagger\conditions.py", line 21, in __init__
    self.time_generated = datetime().now().timestamp()
TypeError: function missing required argument 'year' (pos 1)


18:37:19:| list index out of range
Message:Binance
#COTI/BTC All take-profit targets achieved 😎
Profit: 1.9643% 📈
Period: 9 Hours 36 Minutes ⏰
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 104, in my_event_handler
    await signal_groups.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\signal_groups.py", line 14, in new_signal
    hirn_controller.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 26, in new_signal
    conditions = self.parse_conditions(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 34, in parse_conditions
    result = self.parse(msg)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 78, in parse
    pair = lines[0].split('#')[1]
IndexError: list index out of range


20:25:55:| list index out of range
Message:KUCOIN
#USDT_DODO
LONG
SL 0%
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 104, in my_event_handler
    await signal_groups.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\signal_groups.py", line 14, in new_signal
    hirn_controller.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 26, in new_signal
    conditions = self.parse_conditions(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 34, in parse_conditions
    result = self.parse(msg)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 78, in parse
    pair = lines[0].split('#')[1]
IndexError: list index out of range


20:25:58:| list index out of range
Message:BINANCE
#USDT_DODO
LONG
SL 0%
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 104, in my_event_handler
    await signal_groups.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\signal_groups.py", line 14, in new_signal
    hirn_controller.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 26, in new_signal
    conditions = self.parse_conditions(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 34, in parse_conditions
    result = self.parse(msg)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 78, in parse
    pair = lines[0].split('#')[1]
IndexError: list index out of range


20:26:27:| list index out of range
Message:Binance
#DODO/USDT All entry targets achieved
Average Entry Price: 0.1470 💵
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 104, in my_event_handler
    await signal_groups.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\signal_groups.py", line 14, in new_signal
    hirn_controller.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 26, in new_signal
    conditions = self.parse_conditions(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 34, in parse_conditions
    result = self.parse(msg)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 78, in parse
    pair = lines[0].split('#')[1]
IndexError: list index out of range


20:27:27:| list index out of range
Message:Binance
#DODO/USDT All take-profit targets achieved 😎
Profit: 1.9728% 📈
Period: 1 Minutes ⏰
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 104, in my_event_handler
    await signal_groups.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\signal_groups.py", line 14, in new_signal
    hirn_controller.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 26, in new_signal
    conditions = self.parse_conditions(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 34, in parse_conditions
    result = self.parse(msg)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 78, in parse
    pair = lines[0].split('#')[1]
IndexError: list index out of range


20:28:02:| list index out of range
Message:Huobi.pro
#DODO/USDT Cancelled ❌
Target achieved before entering the entry zone
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 104, in my_event_handler
    await signal_groups.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\signal_groups.py", line 14, in new_signal
    hirn_controller.new_signal(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 26, in new_signal
    conditions = self.parse_conditions(signal)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 34, in parse_conditions
    result = self.parse(msg)
  File "C:\Users\lachl\Documents\GitHub\telebagger\hirn.py", line 78, in parse
    pair = lines[0].split('#')[1]
IndexError: list index out of range


