22:39:25:| 'Trade' object has no attribute 'signal'
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 226, in update_trades_now
    self.coin_trade_data(now_kline_msg)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 49, in coin_trade_data
    trade.update_trade(stream)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 43, in update_trade
    self.save_trade()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 55, in save_trade
    db.save_trade(self)
  File "C:\Users\lachl\Repos\GitHub\telebagger\database_logging.py", line 64, in save_trade
    m_path_on_cloud = paths.SAVE_TRADE + trade.signal.origin.name + '/' + date_string + '.txt'
AttributeError: 'Trade' object has no attribute 'signal'


22:40:14:| [Errno 13] Permission denied: 'trade_results/Hirn/juice/'
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 226, in update_trades_now
    self.coin_trade_data(now_kline_msg)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 49, in coin_trade_data
    trade.update_trade(stream)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 43, in update_trade
    self.save_trade()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 55, in save_trade
    db.save_trade(self)
  File "C:\Users\lachl\Repos\GitHub\telebagger\database_logging.py", line 79, in save_trade
    with open(dj_path_on_local, 'a', encoding="utf8") as f:
PermissionError: [Errno 13] Permission denied: 'trade_results/Hirn/juice/'


22:43:32:| [WinError 183] Cannot create a file when that file already exists: 'trade_results/Hirn/juice/'
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 226, in update_trades_now
    self.coin_trade_data(now_kline_msg)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 49, in coin_trade_data
    trade.update_trade(stream)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 43, in update_trade
    self.save_trade()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 55, in save_trade
    db.save_trade(self)
  File "C:\Users\lachl\Repos\GitHub\telebagger\database_logging.py", line 107, in save_trade
    os.makedirs(dj_path_on_local)
  File "C:\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'trade_results/Hirn/juice/'


22:45:02:| Object of type Trade is not JSON serializable
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 226, in update_trades_now
    self.coin_trade_data(now_kline_msg)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 49, in coin_trade_data
    trade.update_trade(stream)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 43, in update_trade
    self.save_trade()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 55, in save_trade
    db.save_trade(self)
  File "C:\Users\lachl\Repos\GitHub\telebagger\database_logging.py", line 111, in save_trade
    save_trade(trade)
  File "C:\Users\lachl\Repos\GitHub\telebagger\database_logging.py", line 80, in save_trade
    f.write(json.dumps(trade))
  File "C:\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Trade is not JSON serializable


22:50:56:| Object of type Client is not JSON serializable
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 226, in update_trades_now
    self.coin_trade_data(now_kline_msg)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 49, in coin_trade_data
    trade.update_trade(stream)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 43, in update_trade
    self.save_trade()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 55, in save_trade
    db.save_trade(self)
  File "C:\Users\lachl\Repos\GitHub\telebagger\database_logging.py", line 80, in save_trade
    f.write(json.dumps(trade.__dict__))
  File "C:\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Client is not JSON serializable


22:55:22:| 'Trade' object has no attribute 'closed_diff'
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 226, in update_trades_now
    self.coin_trade_data(now_kline_msg)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 49, in coin_trade_data
    trade.update_trade(stream)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 43, in update_trade
    self.save_trade()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 55, in save_trade
    db.save_trade(self)
  File "C:\Users\lachl\Repos\GitHub\telebagger\database_logging.py", line 95, in save_trade
    tradevalue = trade.closed_diff
AttributeError: 'Trade' object has no attribute 'closed_diff'


23:02:35:| Object of type Trade is not JSON serializable
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 226, in update_trades_now
    self.coin_trade_data(now_kline_msg)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 49, in coin_trade_data
    trade.update_trade(stream)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 44, in update_trade
    self.save_trade()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 56, in save_trade
    db.save_trade(self)
  File "C:\Users\lachl\Repos\GitHub\telebagger\database_logging.py", line 81, in save_trade
    f.write(json.dumps(trade))
  File "C:\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Trade is not JSON serializable


23:03:48:| Object of type SpotBasic is not JSON serializable
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 226, in update_trades_now
    self.coin_trade_data(now_kline_msg)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 49, in coin_trade_data
    trade.update_trade(stream)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 44, in update_trade
    self.save_trade()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 56, in save_trade
    db.save_trade(self)
  File "C:\Users\lachl\Repos\GitHub\telebagger\database_logging.py", line 81, in save_trade
    f.write(json.dumps(trade.__dict__))
  File "C:\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SpotBasic is not JSON serializable


23:06:00:| 'Trade' object has no attribute 'origin'
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 226, in update_trades_now
    self.coin_trade_data(now_kline_msg)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 49, in coin_trade_data
    trade.update_trade(stream)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 44, in update_trade
    self.save_trade()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 56, in save_trade
    db.save_trade(self)
  File "C:\Users\lachl\Repos\GitHub\telebagger\database_logging.py", line 104, in save_trade
    realtime_save_trade(tradevalue, trade, now)
  File "C:\Users\lachl\Repos\GitHub\telebagger\database_logging.py", line 22, in realtime_save_trade
    signal_group = trade.origin
AttributeError: 'Trade' object has no attribute 'origin'


23:07:51:| dictionary changed size during iteration
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 218, in update_trades_now
    for t, trades in self.streaming_trades.items():
RuntimeError: dictionary changed size during iteration


23:09:23:| dictionary changed size during iteration
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 218, in update_trades_now
    for t, trades in self.streaming_trades.items():
RuntimeError: dictionary changed size during iteration


23:10:20:| dictionary changed size during iteration
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 218, in update_trades_now
    for t, trades in self.streaming_trades.items():
RuntimeError: dictionary changed size during iteration


23:12:37:| dictionary changed size during iteration
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 218, in update_trades_now
    for t, trades in self.streaming_trades.items():
RuntimeError: dictionary changed size during iteration


23:13:50:| dictionary changed size during iteration
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 218, in update_trades_now
    for t, trades in self.streaming_trades.items():
RuntimeError: dictionary changed size during iteration


