17:11:16:| dictionary changed size during iteration
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 218, in update_trades_now
    for t, trades in self.streaming_trades.items():
RuntimeError: dictionary changed size during iteration


17:40:05:| 'Trade' object has no attribute 'conditions'
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 226, in update_trades_now
    self.coin_trade_data(now_kline_msg)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 49, in coin_trade_data
    trade.update_trade(stream)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 38, in update_trade
    self.conditions.check_timeout(self)
AttributeError: 'Trade' object has no attribute 'conditions'


17:40:20:| 'Trade' object has no attribute 'conditions'
Message:/dump
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 104, in telegram_command
    await self.trade_stream.dump_stream()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 86, in dump_stream
    self.checkupdate()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 62, in checkupdate
    closed_trades = self.stoptrade()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 185, in stoptrade
    print("Removing ", stoptrade, 'for reason', stoptrade.status)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 65, in __str__
    return self.pair  + '_' + self.conditions.signal.origin.name + '_' + str(self.id)
AttributeError: 'Trade' object has no attribute 'conditions'


17:40:29:| 'Trade' object has no attribute 'conditions'
Message:/dump
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 104, in telegram_command
    await self.trade_stream.dump_stream()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 86, in dump_stream
    self.checkupdate()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 62, in checkupdate
    closed_trades = self.stoptrade()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 185, in stoptrade
    print("Removing ", stoptrade, 'for reason', stoptrade.status)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 65, in __str__
    return self.pair  + '_' + self.conditions.signal.origin.name + '_' + str(self.id)
AttributeError: 'Trade' object has no attribute 'conditions'


17:45:13:| module 'database_logging' has no attribute 'save_trade'
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 226, in update_trades_now
    self.coin_trade_data(now_kline_msg)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 49, in coin_trade_data
    trade.update_trade(stream)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 44, in update_trade
    self.save_trade()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 56, in save_trade
    db.save_trade(self)
AttributeError: module 'database_logging' has no attribute 'save_trade'


17:45:52:| 'NoneType' object has no attribute 'get_historical_klines'
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 222, in update_trades_now
    klines = trade.client.get_historical_klines(symbol=trade.pair, interval=trade.client.KLINE_INTERVAL_1MINUTE , start_str=time)
AttributeError: 'NoneType' object has no attribute 'get_historical_klines'


17:46:16:| dictionary changed size during iteration
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 218, in update_trades_now
    for t, trades in self.streaming_trades.items():
RuntimeError: dictionary changed size during iteration


18:21:44:| 'Trade' object has no attribute 'replace'
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 226, in update_trades_now
    self.coin_trade_data(now_kline_msg)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 49, in coin_trade_data
    trade.update_trade(stream)
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 44, in update_trade
    self.save_trade()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade.py", line 56, in save_trade
    db.save_closed_trade(self)
  File "C:\Users\lachl\Repos\GitHub\telebagger\database_logging.py", line 100, in save_closed_trade
    close_live_view(trade, json_filepath)
  File "C:\Users\lachl\Repos\GitHub\telebagger\database_logging.py", line 61, in close_live_view
    active_filepath = closed_filepath.replace('closed', 'active')
AttributeError: 'Trade' object has no attribute 'replace'


18:22:31:| 'NoneType' object has no attribute 'get_historical_klines'
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 222, in update_trades_now
    klines = trade.client.get_historical_klines(symbol=trade.pair, interval=trade.client.KLINE_INTERVAL_1MINUTE , start_str=time)
AttributeError: 'NoneType' object has no attribute 'get_historical_klines'


18:23:00:| Closing_trade1666434094213does not seem to exist

18:23:25:| Closing_trade1666434144353does not seem to exist

19:16:07:| 'Trade' object has no attribute 'client'
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 236, in update_trades_now
    klines = trade.client.get_historical_klines(symbol=trade.pair, interval=trade.client.KLINE_INTERVAL_1MINUTE , start_str=time)
AttributeError: 'Trade' object has no attribute 'client'


19:17:27:| 'Trade' object has no attribute 'client'
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 237, in update_trades_now
    klines = config.get_binance_config().get_historical_klines(symbol=trade.pair, interval=trade.client.KLINE_INTERVAL_1MINUTE , start_str=time)
AttributeError: 'Trade' object has no attribute 'client'


19:17:59:| Closing_trade1666437358581does not seem to exist

19:18:39:| 'Trade' object has no attribute 'client'
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 237, in update_trades_now
    klines = config.get_binance_config().get_historical_klines(symbol=trade.pair, interval=trade.client.KLINE_INTERVAL_1MINUTE , start_str=time)
AttributeError: 'Trade' object has no attribute 'client'


19:19:48:| APIError(code=-1100): Illegal characters found in parameter 'interval'; legal range is '^[a-zA-Z0-9]{1,36}$'.
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 237, in update_trades_now
    klines = config.get_binance_config().get_historical_klines(symbol=trade.pair, interval='KLINE_INTERVAL_1MINUTE' , start_str=time)
  File "C:\Users\lachl\Repos\GitHub\telebagger\.venv\lib\site-packages\binance\client.py", line 934, in get_historical_klines
    return self._historical_klines(
  File "C:\Users\lachl\Repos\GitHub\telebagger\.venv\lib\site-packages\binance\client.py", line 973, in _historical_klines
    first_valid_ts = self._get_earliest_valid_timestamp(symbol, interval, klines_type)
  File "C:\Users\lachl\Repos\GitHub\telebagger\.venv\lib\site-packages\binance\client.py", line 904, in _get_earliest_valid_timestamp
    kline = self._klines(
  File "C:\Users\lachl\Repos\GitHub\telebagger\.venv\lib\site-packages\binance\client.py", line 883, in _klines
    return self.get_klines(**params)
  File "C:\Users\lachl\Repos\GitHub\telebagger\.venv\lib\site-packages\binance\client.py", line 868, in get_klines
    return self._get('klines', data=params, version=self.PRIVATE_API_VERSION)
  File "C:\Users\lachl\Repos\GitHub\telebagger\.venv\lib\site-packages\binance\client.py", line 371, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\lachl\Repos\GitHub\telebagger\.venv\lib\site-packages\binance\client.py", line 334, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\lachl\Repos\GitHub\telebagger\.venv\lib\site-packages\binance\client.py", line 315, in _request
    return self._handle_response(self.response)
  File "C:\Users\lachl\Repos\GitHub\telebagger\.venv\lib\site-packages\binance\client.py", line 324, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1100): Illegal characters found in parameter 'interval'; legal range is '^[a-zA-Z0-9]{1,36}$'.


19:21:53:| dictionary changed size during iteration
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 233, in update_trades_now
    for t, trades in self.streaming_trades.items():
RuntimeError: dictionary changed size during iteration


19:23:27:| dictionary changed size during iteration
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 234, in update_trades_now
    for t, trades in self.streaming_trades.items():
RuntimeError: dictionary changed size during iteration


19:24:38:| 'str' object has no attribute 'pair'
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 239, in update_trades_now
    klines = config.get_binance_config().get_historical_klines(symbol=trade.pair, interval=config.get_binance_config().KLINE_INTERVAL_1MINUTE , start_str=time)
AttributeError: 'str' object has no attribute 'pair'


19:25:35:| 'str' object has no attribute 'pair'
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 239, in update_trades_now
    klines = config.get_binance_config().get_historical_klines(symbol=trade.pair, interval=config.get_binance_config().KLINE_INTERVAL_1MINUTE , start_str=time)
AttributeError: 'str' object has no attribute 'pair'


19:27:14:| dictionary changed size during iteration
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 234, in update_trades_now
    for trades in self.streaming_trades.items():
RuntimeError: dictionary changed size during iteration


19:29:02:| dictionary changed size during iteration
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 234, in update_trades_now
    for trades in self.streaming_trades.items():
RuntimeError: dictionary changed size during iteration


19:29:44:| 'dict_items' object is not subscriptable
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 234, in update_trades_now
    for trades in self.streaming_trades.items()[:]:
TypeError: 'dict_items' object is not subscriptable


19:30:33:| unhashable type: 'slice'
Message:/now
Except:Traceback (most recent call last):
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 120, in my_event_handler
    await self.telegram_command(signal)
  File "C:\Users\lachl\Repos\GitHub\telebagger\telebagger.py", line 95, in telegram_command
    self.trade_stream.update_trades_now()
  File "C:\Users\lachl\Repos\GitHub\telebagger\trade_stream.py", line 234, in update_trades_now
    for trades in self.streaming_trades[:].items():
TypeError: unhashable type: 'slice'


19:30:59:| Closing_trade1666438175827does not seem to exist

